language: node_js
node_js:
- '0.10'
deploy:
  provider: releases
  api_key:
    secure: Xxc5MKZ9PSI1ODNEbj3uqlb36DgSYowUhz4EejQfj7Poy5vG9jtuudI0KgYGutVm4PmKOwO4iaRgWmVdZMJqRm8LKBl4nMFS7+3+leqstkmrDXDNg9JGJ83xrKuXLIE9rua28EhuA8PWK7UO4rx7eT6IrHSpy6SOBpPN9q7pE1E=
  file:
    - "dist/spromise.js"
    - "dist/spromise-debug.js"
    - "dist/spromise-lib.js
    - "dist/spromise-lib-debug.js
  on:
    repo: MiguelCastillo/spromise
    tags: true
    all_branches: true
